[package]
name = "rtc-mdns"
version = "0.0.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2024"
description = "RTC mDNS in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/rtc-mdns"
homepage = "https://ortc.rs"
repository = "https://github.com/webrtc-rs/rtc/tree/master/reserved/rtc-mdns"

[dependencies]

[dev-dependencies]
