[workspace]
members = [
    "rtc",
    "rtc-datachannel",
    "rtc-dtls",
    "rtc-ice",
    "rtc-rtcp",
    "rtc-rtp",
    "rtc-sctp",
    "rtc-sdp",
    "rtc-shared",
    "rtc-srtp",
    "rtc-stun",
    "reserved/rtc-turn",
    "reserved/rtc-interceptor",
    "reserved/rtc-mdns",
    "reserved/rtc-media",
]
resolver = "2"

[profile.dev]
opt-level = 0
