[workspace]
members = [
    "examples",
    "rtc",
    "rtc-datachannel",
    "rtc-dtls",
    "rtc-ice",
    "rtc-interceptor",
    "rtc-media",
    "rtc-mdns",
    "rtc-rtcp",
    "rtc-rtp",
    "rtc-sctp",
    "rtc-sdp",
    "rtc-shared",
    "rtc-srtp",
    "rtc-stun",
    "rtc-turn",
]
resolver = "2"

[workspace.package]
version = "0.3.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2024"
license = "MIT/Apache-2.0"
homepage = "https://ortc.rs"
repository = "https://github.com/webrtc-rs/rtc"

[profile.dev]
opt-level = 0
