[package]
name = "rtc-signal"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Examples of WebRTC.rs stack's signaling"
license.workspace = true
documentation = "https://docs.rs/rtc-signal"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tokio.workspace = true
anyhow = "1"
base64 = "0.22.1"
lazy_static = "1"
hyper = { version = "0.14.27", features = ["full"] }
