[package]
name = "rtc-signal"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Examples of WebRTC.rs stack"
license.workspace = true
documentation = "https://docs.rs/examples"
homepage.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1"
base64 = "0.22.1"
lazy_static = "1"
hyper = { version = "0.14.27", features = ["full"] }
