[package]
name = "rtc-datachannel"
version = "0.2.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2021"
description = "RTC DataChannel in Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/rtc-datachannel"
homepage = "https://ortc.rs"
repository = "https://github.com/webrtc-rs/rtc/tree/master/rtc-datachannel"

[dependencies]
shared = { version = "0.2.0", path = "../rtc-shared", package = "rtc-shared", default-features = false, features = ["marshal"] }
sctp = { version = "0.2.0", path = "../rtc-sctp", package = "rtc-sctp" }

bytes = "1.5.0"
log = "0.4.21"
sansio = "1.0.1"

[dev-dependencies]
env_logger = "0.11.3"
chrono = "0.4.35"
